CREATE PROCEDURE FI_SP_IncBeneficiario
    @CPF           VARCHAR (14),    
	@NOME          VARCHAR (255),
	@IDCLIENTE     BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END